language: ruby
bundler_args: --without benchmarks
script:
  - bundle exec rake spec
before_install:
  - gem --version
  - |
    bash -c " # Install MySQL 5.7 if DB=mysql57
    if [[ x$DB =~ mysql57 ]]; then
      bash .travis_mysql57.sh
    fi
    "
  - |
    bash -c " # Install MariaDB if DB=mariadb
    if [[ x$DB =~ xmariadb ]]; then
      sudo bash .travis_mariadb.sh '$DB'
    fi
    "
  - |
    bash -c " # Install MySQL is OS=darwin
    if [[ x$OSTYPE =~ ^xdarwin ]]; then
      brew install mysql
      mysql.server start
    fi
    "
  - |
    bash -c " # Configure SSL support
    sudo bash .travis_ssl.sh
    "
  - mysqld --version
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test"
os:
  - linux
matrix:
  include:
    - rvm: 2.0.0
      env: DB=mysql57
